# Generated by Django 4.0.4 on 2022-05-21 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PerTakip', '0002_alter_perizindurum_id_alter_pertakipkayit_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perizindurum',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='pertakipkayit',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='pertakipnotlar',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='ptkduyurular',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='ptkfirma',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
