# Generated by Django 4.0.4 on 2022-05-21 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PerTakip', '0005_alter_perizindurum_peradisoyadi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perizindurum',
            name='PerAdiSoyadi',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Personel Adı-Soyadı'),
        ),
    ]
