# Generated by Django 4.0.4 on 2022-05-21 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PerTakip', '0007_pertakipkayit_ptkfirmabilgi'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pertakipkayit',
            name='PTKFirmaBilgi',
        ),
    ]
