# Generated by Django 4.0.4 on 2022-05-23 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PerTakip', '0008_remove_pertakipkayit_ptkfirmabilgi'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perizindurum',
            name='PerIzinSuresi',
        ),
        migrations.AddField(
            model_name='perizindurum',
            name='PerIzinSuresiGun',
            field=models.FloatField(blank=True, null=True, verbose_name='İzin Süresi Gün'),
        ),
        migrations.AddField(
            model_name='perizindurum',
            name='PerIzinSuresiSaat',
            field=models.FloatField(blank=True, null=True, verbose_name='İzin Süresi Saat'),
        ),
    ]
