# Generated by Django 4.0.4 on 2022-05-25 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PerTakip', '0009_remove_perizindurum_perizinsuresi_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perizindurum',
            name='PerIzinSuresiGun',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='İzin Süresi Gün'),
        ),
        migrations.AlterField(
            model_name='perizindurum',
            name='PerIzinSuresiSaat',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='İzin Süresi Saat'),
        ),
    ]
