# Generated by Django 4.0.4 on 2022-05-26 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PerTakip', '0011_pertakipkayit_ptkhakedilenizin'),
    ]

    operations = [
        migrations.AddField(
            model_name='pertakipkayit',
            name='PTKHakedilenIzinYil',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Hakedilen İzin Yıl'),
        ),
    ]
