# Generated by Django 4.0.4 on 2022-05-30 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PerTakip', '0013_rename_ptkhakedilenizin_pertakipkayit_ptkhakedilenizingun_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perizindurum',
            name='PerIzinSuresiGun',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='İzin Süresi Gün'),
        ),
        migrations.AlterField(
            model_name='perizindurum',
            name='PerIzinSuresiSaat',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='İzin Süresi Saat'),
        ),
        migrations.AlterField(
            model_name='pertakipkayit',
            name='PTKHakedilenIzinGun',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Hakedilen İzin Süresi Gün'),
        ),
        migrations.AlterField(
            model_name='pertakipkayit',
            name='PTKHakedilenIzinYil',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Hakedilen İzin Yıl'),
        ),
        migrations.AlterField(
            model_name='pertakipkayit',
            name='PTKIzinSuresiGun',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Kullanılan İzin Süresi Gün'),
        ),
    ]
