# Generated by Django 4.0.4 on 2022-05-31 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PerTakip', '0014_alter_perizindurum_perizinsuresigun_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pertakipkayit',
            name='PTKkalanizin',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Kullanılan İzin Süresi Gün'),
        ),
    ]
