# Generated by Django 4.0.4 on 2022-05-21 10:38

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('TalepYonetimi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SatisGorusmesi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SatisKonu', models.CharField(max_length=50, verbose_name='Başlık')),
                ('SatisGorusulenKisi', models.CharField(max_length=50, verbose_name='Yetkili Kişi')),
                ('SatisGorusulenKisiTelefon', models.CharField(blank=True, max_length=20, null=True, verbose_name='Yetkili Telefon / Dahili')),
                ('SatisGorusulenKisiMail', models.CharField(blank=True, max_length=50, null=True, verbose_name='Yetkili E-Posta Adresi')),
                ('SatisDurumu', models.CharField(choices=[('Açık', 'Açık'), ('Kapalı', 'Kapalı'), ('Geri Dönülecek', 'Geri Dönülecek')], default='0', max_length=50, verbose_name='Durum')),
                ('SatisAciklama', ckeditor.fields.RichTextField(verbose_name='Açıklama')),
                ('SatisDosya', models.FileField(blank=True, null=True, upload_to='Dosya/', verbose_name='Çağrı Dosyası Ekle')),
                ('SatisBaslamaTarihi', models.DateTimeField(auto_now_add=True, null=True)),
                ('SatisKapanmaTarihi', models.DateTimeField(auto_now_add=True, null=True)),
                ('SatisAktif', models.BooleanField(default=True, verbose_name='silmek için Onayı kaldırın..!!!')),
                ('SatisKurum', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='TalepYonetimi.kurumlar', verbose_name='Görüşülen Kurum')),
                ('SatisUser', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('SatisUygulama', models.ForeignKey(default='1', null=True, on_delete=django.db.models.deletion.SET_NULL, to='TalepYonetimi.uygulama', verbose_name='Uygulama')),
            ],
            options={
                'verbose_name_plural': 'Satış Görüşmeleri',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='STSsatisNotlar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('satisNotlarKonu', models.CharField(blank=True, max_length=50, null=True, verbose_name='Konu')),
                ('satisMetin', ckeditor.fields.RichTextField(help_text='Çağrı ile İlgili Tüm Notlarınızı ekleyebilirsiniz..', max_length=2000, null=True, verbose_name='İçerik')),
                ('satisOlusturmaTarihi', models.DateTimeField(auto_now_add=True, null=True)),
                ('satisNotDosya', models.FileField(blank=True, null=True, upload_to='STSNotlar/', verbose_name='Çağrı Notlarına Dosya Ekle')),
                ('satisNotAktif', models.BooleanField(default=True, verbose_name='silmek için Onayı kaldırın..!!!')),
                ('satisGorusmesi', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cagriNotlar', to='Satis.satisgorusmesi')),
                ('satisNotUser', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Cağrı Notları',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='STSIhaleTakip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IhaleYapan', models.CharField(blank=True, max_length=550, null=True, verbose_name='İhalenin Kurumu')),
                ('IhaleYayinTarihi', models.CharField(blank=True, max_length=550, null=True, verbose_name='İhalenin Yayın Tarihi')),
                ('IhaleTarihi', models.CharField(blank=True, max_length=550, null=True, verbose_name='İhalenin Tarihi')),
                ('IhaleKayitTarihi', models.DateTimeField(auto_now_add=True, null=True)),
                ('IhaleAdi', models.CharField(blank=True, max_length=550, null=True, verbose_name='İhalenin Adı')),
                ('IhaleAciklama', models.CharField(blank=True, max_length=550, null=True, verbose_name='İhalenin Açıklama')),
                ('IhaleAktif', models.BooleanField(default=True, verbose_name='Biten İhale için Onayı kaldırın..!!!')),
                ('IhaleDosya', models.FileField(blank=True, null=True, upload_to='IhaleTakip/', verbose_name='İhale Dosya Ekle')),
                ('IhaleUser', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-IhaleTarihi'],
            },
        ),
        migrations.CreateModel(
            name='SatisSozlesmeler',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SozlesmeBaslangicTarihi', models.DateField(help_text='Tarihi Girişinde örn. 22/11/2018 şeklinde / işareti koyunuz.', verbose_name='Sozlesme Başlangıç Tarihi')),
                ('SozlesmeBitisTarihi', models.DateField(help_text='Tarihi Girişinde örn. 22/11/2018 şeklinde / işareti koyunuz.', verbose_name='Sozlesme Bitiş Tarihi')),
                ('SozlesmeKonusu', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Sozlesme Konusu')),
                ('SozlesmeDurumu', models.CharField(choices=[('Devam Eden', 'Devam Eden'), ('Süresi Biten', 'Süresi Biten')], default='Devam Eden', max_length=50, verbose_name='Durum')),
                ('SozlesmeAktif', models.BooleanField(default=True, verbose_name='silmek için Onayı kaldırın..!!!')),
                ('SozlesmeKurum', models.ForeignKey(max_length=250, null=True, on_delete=django.db.models.deletion.SET_NULL, to='TalepYonetimi.kurumlar', verbose_name='Sozlesme Yapılan Kurum')),
                ('SozlesmeUser', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Sözleşme Takip',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='SatisDuyurular',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DuyuruTarihi', models.DateTimeField(auto_now_add=True)),
                ('DuyuruBaslik', models.CharField(blank=True, default='', max_length=250, null=True, verbose_name='Duyurunun Konusu')),
                ('DuyuruAciklama', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Duyuru Metni')),
                ('DuyuruAktif', models.BooleanField(default=True, verbose_name='silmek için Onayı kaldırın..!!!')),
                ('DuyuruUser', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Duyurular',
                'ordering': ['-id'],
            },
        ),
    ]
