# Generated by Django 4.0.5 on 2022-09-01 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Satis', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='satisduyurular',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='satisgorusmesi',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='satissozlesmeler',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='stsihaletakip',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='stssatisnotlar',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
